branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
openPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
autoCloseIssue: true
